create schema if not exists digitalbookkeeping;
set schema 'digitalbookkeeping';

create table if not exists person (
    id bigint generated by default as identity,
    first_name varchar not null,
    middle_name varchar not null,
    last_name varchar not null,
    birthdate date not null ,
    constraint person_pk PRIMARY KEY (id),
    constraint full_name_constraint UNIQUE (first_name, middle_name, last_name)
);

create table if not exists book (
    id bigint generated by default  as identity,
    name varchar not null,
    author varchar not null,
    year date not null,
    taken_by bigint,
    constraint book_pk primary key (id),
    constraint person_fk foreign key (taken_by) references person(id) on delete set null
)